#!/usr/bin/env python

"""Amulet tests on a basic manila deployment on cosmic-rocky.
"""

from basic_deployment import ManilaBasicDeployment

if __name__ == '__main__':
    deployment = ManilaBasicDeployment(series='cosmic')
    deployment.run_tests()
