#!/usr/bin/env python

"""Amulet tests on a basic manila deployment on disco-stein.
"""

from basic_deployment import ManilaBasicDeployment

if __name__ == '__main__':
    deployment = ManilaBasicDeployment(series='disco')
    deployment.run_tests()
