#!/usr/bin/env python

"""Amulet tests on a basic manila deployment on artful-pike.
"""

from basic_deployment import ManilaBasicDeployment

if __name__ == '__main__':
    deployment = ManilaBasicDeployment(series='artful')
    deployment.run_tests()
