#!/usr/bin/env python

"""Amulet tests on a basic manila deployment on bionic-train.
"""

from basic_deployment import ManilaBasicDeployment

if __name__ == '__main__':
    deployment = ManilaBasicDeployment(series='bionic',
                                       openstack='cloud:bionic-train',
                                       source='cloud:bionic-train')
    deployment.run_tests()
