#!/usr/bin/env python

"""Amulet tests on a basic manila deployment on xenial-ocata.
"""

from basic_deployment import ManilaBasicDeployment

if __name__ == '__main__':
    deployment = ManilaBasicDeployment(series='xenial')
    deployment.run_tests()
