#!/usr/bin/env python

"""Amulet tests on a basic manila deployment on yakkety-newton
"""

from basic_deployment import ManilaBasicDeployment

if __name__ == '__main__':
    deployment = ManilaBasicDeployment(series='yakkety')
    deployment.run_tests()
