#!/usr/bin/env python

"""Amulet tests on a basic manila deployment on zesty-ocata.
"""

from basic_deployment import ManilaBasicDeployment

if __name__ == '__main__':
    deployment = ManilaBasicDeployment(series='zesty')
    deployment.run_tests()
